# Generated by Django 5.0.8 on 2024-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonasModelo",
            fields=[
                (
                    "dni",
                    models.CharField(
                        db_collation="utf8mb3_spanish_ci",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(db_collation="utf8mb3_spanish_ci", max_length=50),
                ),
                (
                    "nombre",
                    models.CharField(db_collation="utf8mb3_spanish_ci", max_length=50),
                ),
                ("externo", models.IntegerField()),
                ("responsable", models.IntegerField()),
                ("cientifico", models.IntegerField()),
                (
                    "superusuario",
                    models.IntegerField(db_comment="superusuario de vehículos"),
                ),
                ("baja", models.IntegerField()),
                ("carnet", models.IntegerField()),
                ("superusuario_intranet", models.IntegerField()),
                (
                    "directorio",
                    models.IntegerField(
                        db_comment="1 si aparece en el directorio web, 0 en caso contrario"
                    ),
                ),
                ("no_persona", models.IntegerField(blank=True, null=True)),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nie",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=11,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "nrp",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nss",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(db_collation="utf8mb3_spanish_ci", max_length=1),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "pais_nacimiento",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "mail_institucional",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "mail_alternativo",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "telefono_personal_fijo",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "telefono_personal_movil",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "domicilio",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "localidad_domicilio",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "provincia_domicilio",
                    models.CharField(
                        blank=True,
                        db_collation="utf8mb3_spanish_ci",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("id_ubicacion", models.IntegerField(blank=True, null=True)),
                ("foto", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "personas",
                "managed": False,
            },
        ),
    ]
